  <footer class="container text-center mt-5">
    <div class="inner">
    &copy 2018 - <?=APP_NAME?> Todos os direitos reservados.
    <a href="http://brunodamiao.com.br" target="_blank">by designer Bruno</a>
    <!-- </div> -->
    </footer>


  <!-- Scripts -->
    <script src="/assets/jquery.min.js"></script>
    <script src="/assets/libs/bootstrap/js/popper.min.js"></script>
    <script src="/assets/libs/bootstrap/js/bootstrap.min.js"></script>

  <script>
  jQuery(function($){


    $( ".nav-link" ).click(function() {
      var data  = $(this).attr('id');
      // alert('oi '+data);
      $( "#DBDrive" ).prop("value", data);
    });

    $( "#btnUser" ).click(function() {
      $( "#pnlUser" ).removeClass('d-none').slideDown();
      $( "#pnlCon" ).slideUp().addClass('d-none');

      $( "#btnSave" ).addClass('btn-success');
      $( "#btnSave" ).prop("type", "submit");
    });

    $( "#btnCon" ).click(function() {
      $( "#pnlCon" ).removeClass('d-none').slideDown();
      $( "#pnlUser" ).slideUp().addClass('d-none');

      $( "#btnSave" ).removeClass('btn-success');
      $( "#btnSave" ).addClass('btn-secondary');
      $( "#btnSave" ).prop("type", "button");
    });

  });

  </script>

</body>
</html>