<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
    <title> <?=APP_NAME?> - <?=$this->getTitle();?> </title>
    <link rel="icon" type="image/png" href="<?=PATH_FAVICON?>" />

    <!-- Style Bootstrap -->
    <link rel="stylesheet" href="/assets/libs/bootstrap/css/bootstrap.min.css">
    <!-- <link rel="stylesheet" href="/assets/home/setup.css"> -->
</head>
<body>