<?php

  $view     = $this->getData();
	$baseURI  = '/auth';

	$msgEmail = getDataInput('user_email') ?? '';
  $msgSenha = getDataInput('user_password') ?? '';

?>

    <section class="material-half-bg">
      <div class="cover"></div>
    </section>

    <section class="login-content">

      <div class="logo">
        <h1> <?=$view['data']?> </h1>
        <!-- <h1><img src="/<?//=PATH_LOGO?>" alt="" width="190"></h1> -->
      </div>

      <div class="login-box">
        <form class="login-form" action="/auth/login" method="post">
          <h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>SIGN IN</h3>
          <?php
    			showMessageFlash('primary');
    			showMessageFlash('success');
    			showMessageFlash('info');
    			showMessageFlash('warning');
    			showMessageFlash('danger');
    		  ?>
          <div class="form-group">
            <label class="control-label">USERNAME</label>
            <input class="form-control" name="user_email" type="text" placeholder="Email" autofocus>
          </div>
          <div class="form-group">
            <label class="control-label">PASSWORD</label>
            <input class="form-control" name="user_password" type="password" placeholder="Password">
          </div>
          <div class="form-group">
            <div class="utility">
              <div class="animated-checkbox">
                <label>
                  <input type="checkbox"><span class="label-text">Stay Signed in</span>
                </label>
              </div>
              <p class="semibold-text mb-2"><a href="#" data-toggle="flip">Forgot Password ?</a></p>
            </div>
          </div>
          <div class="form-group btn-container">
            <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-sign-in fa-lg fa-fw"></i>SIGN IN</button>
          </div>
        </form>

        <form class="forget-form" action="/auth/forgotin" method="post">
          <h3 class="login-head"><i class="fa fa-lg fa-fw fa-lock"></i>Forgot Password ?</h3>

          <div class="form-group">
            <label class="control-label">EMAIL</label>
            <input class="form-control" type="text" name="user_email" placeholder="Email">
          </div>
          <div class="form-group btn-container">
            <button type="submit" class="btn btn-primary btn-block"><i class="fa fa-unlock fa-lg fa-fw"></i>RESET</button>
          </div>
          <div class="form-group mt-3">
            <p class="semibold-text mb-0"><a href="#" data-toggle="flip"><i class="fa fa-angle-left fa-fw"></i> Back to Login</a></p>
          </div>
        </form>
      </div>

    </section>


