<?php

	$baseURI  = '/auth';

	$msgEmail = getDataInput('user_email') ?? '';
  	$msgSenha = getDataInput('user_password') ?? '';

?>

	<main role="main" class="inner cover">

		<?php
			showMessageFlash('primary');
			showMessageFlash('success');
			showMessageFlash('info');
			showMessageFlash('danger');
			showMessageFlash('warning');
		?>

		<form action="/auth/login" method="post" class="form-signin">
			<img class="mb-4" src="/<?=PATH_LOGO2?>" alt="" >

			<h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>

			<label for="inputEmail" class="sr-only">Email address</label>
			<input type="email" id="user_email" name="user_email" class="form-control bmail" placeholder="Email address" requiredx autofocusx>

			<label for="inputPassword" class="sr-only">Password</label>
			<input type="password" id="user_password" name="user_password" class="form-control bpass" placeholder="Password" requiredx>

			<div class="checkbox mb-3">
				<label>
					<input type="checkbox" value="remember-me"> Remember me
				</label>
			</div>

			<button type="submit" class="btn btn-lg btn-primary btn-block">Sign in</button>

			<!-- <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p> -->
			<p class="mt-4 mb-3 text-muted">
				forgot your password? <a href="/auth/forgot">click here</a>
				<br> new user? <a href="/auth/create">create new account</a>
			</p>
		</form>
	</main>


