<?php

    $baseURI  = '/auth';
    $msgEmail = getDataInput('user_email') ?? '';
    $msgSenha = getDataInput('user_password') ?? '';

?>

<main role="main" class="inner cover">
  
  <?php
      
      showMessageFlash('primary');
      showMessageFlash('success');
      showMessageFlash('info');
      showMessageFlash('danger');
      showMessageFlash('warning');

    ?>

    <form action="/auth/forgot" method="post" class="form-signin">
      <img class="mb-4" src="/<?=PATH_LOGO2?>" alt="" >

      <h1 class="h3 mb-3 font-weight-normal">Forgot your password</h1>

      <label for="inputEmail" class="sr-only">Email address</label>
      <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
      
      <button type="submit" class="mt-4 btn btn-lg btn-primary btn-block">Enviar</button>
      
      <p class="mt-4 mb-3 text-muted">
        sign in? <a href="/auth">click here</a>
        <br> new user? <a href="/auth/create">create new account</a>
      </p>
    </form>

</main>

