    <footer class="mastfoot mt-auto">
      <div class="inner">
        &copy 2018 - <?=APP_HEADER?> Todos os direitos reservados.
        <a href="http://brunodamiao.com.br" target="_blank">by designer Bruno</a>
      </div>
    </footer>

  </div>




  <!-- Scripts -->
  <script src="/assets/jquery.min.js"></script>
  <!-- <script src="<?=$uriAssets;?>/js/init.js"></script> -->
  <!-- <script src="<?=$uriAssets;?>/js/init.js"></script> -->

  </body>
</html>