<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>

    <title> <?=APP_HEADER?> - <?=$this->getTitle();?> </title>
    <link rel="icon" type="image/png" href="<?=PATH_FAVICON?>" />

	<?php
		$uriAssets = '/assets/site';
		// $uriCustom = '/assets/site';
	?>
	
	<!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">

    <!-- Style Bootstrap -->
    <link rel="stylesheet" href="/assets/libs/Bootstrap/css/Bootstrap.min.css">
    
    <!-- Style Signin -->
    <!-- <link rel="stylesheet" href="/assets/home/signin.css"> -->

</head>

<body class="text-center">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">

