
	<header class="masthead mb-auto">
		<div class="inner">
			<h3 class="masthead-brand">Brand</h3>
			<nav class="nav nav-masthead justify-content-center">
			    <a class="nav-link active" href="/">Home</a>
			    <a class="nav-link" href="/about">About</a>
		        <a class="nav-link" href="/contact">Contact</a>
		        <a class="nav-link" href="/auth">LogIn</a>
			</nav>
		</div>
	</header>

