


    <!-- Essential javascripts for application to work-->
    <script src="/assets/theme/js/jquery-3.2.1.min.js"></script>
    <script src="/assets/theme/js/popper.min.js"></script>
    <script src="/assets/theme/js/bootstrap.min.js"></script>
    <script src="/assets/theme/js/main.js"></script>
    <!-- The javascript plugin to display page loading on top-->
    <script src="/assets/theme/js/plugins/pace.min.js"></script>
    <script type="text/javascript">
      // Login Page Flipbox control
      $('.login-content [data-toggle="flip"]').click(function() {
        $('.login-box').toggleClass('flipped');
        return false;
      });
    </script>
  </body>
</html>