<?php
  $root  = '/admin/user';
  $view = $this->getData();
  $data = ($view['data'])?? '';
  $level = ($view['level'])?? '';

  if ($data) {
    $formTitle  = 'Edit';
    $msgAction  = $root.'/edit/'.$data->user_id;
    $btnAction  = '<i class="fa fa-edit m-right-xs"></i> Edit';
    $msgId      = ($data->user_id) ?? '';
    $msglevel   = ($data->level_id) ?? '1';
    $msgCategory= ($data->level_category) ?? '';
    $msgCatName = ($data->level_name) ?? '';
    $msgName    = ($data->user_name) ?? '';
    $msgEmail   = ($data->user_email) ?? '';
    $msgObs     = ($data->user_obs) ?? '';
    $msgAuthor  = ($data->name_author) ?? '';
    $msgCreated = getDateTimePTbr($data->user_created);
    $msgUpdated = getDateTimePTbr($data->user_updated);
  }else{
    $formTitle  = 'Create';
    $msgAction  = $root.'/create';
    $btnAction  = '<i class="fa fa-fw fa-lg fa-check-circle"></i>Register';
    $msglevel   = getDataInput('level_id')?? '1';
    $msgCategory= getDataInput('level_category')?? '';
    $msgName    = getDataInput('user_name')?? '';
    $msgEmail   = getDataInput('user_email')?? '';
    $msgObs     = getDataInput('user_obs')?? 'informe obs';
    $msgAuthor  = getDataInput('name_author')?? 'Author: --';
    $msgCreated = getDataInput('name_created')?? 'Create: --';
    $msgUpdated = getDataInput('name_updated')?? 'Update: --';
  }

  $thumb      = ($data->user_thumb) ?? '';
  $msgThumb   = '/'.showThumb($thumb,'user');
  $msgShow    = ($data->user_show) ?? '';
  // $btnBack    = '<i class="fa fa-chevron-left m-right-xs"></i> Voltar';
  $btnBack    = '<i class="fa fa-fw fa-lg fa-times-circle "></i> Voltar';
?>

    <main class="app-content">
      <div class="app-title">
        <div>
          <h1><i class="fa fa-edit"></i> <?=$this->getTitle()?> </h1>
          <p> <?=APP_SLOGAN?> </p>
        </div>
        <ul class="app-breadcrumb breadcrumb">
          <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
          <li class="breadcrumb-item">Cadastro</li>
          <li class="breadcrumb-item">User</li>
          <li class="breadcrumb-item"><a href="#"><?=$formTitle?></a></li>
        </ul>
      </div>
      <div class="row">

        <div class="col-md-4">
          <div class="tile">
            <h3 class="tile-title">Thumb</h3>

            <div class="tile-body">
                <img src="<?=$msgThumb;?>" id="avatar" class="img-responsive img-thumbnail " title="<?='Avatar'?>">
            </div>
            <div class="tile-footer"></div>

          </div>
        </div>

        <div class="col-md-8">
          <div class="tile">
            <h3 class="tile-title"> <?=$formTitle;?> record </h3>
            <?php
              showMessageFlash('primary');
              showMessageFlash('success');
              showMessageFlash('info');
              showMessageFlash('danger');
              showMessageFlash('warning');
            ?>
            <form action="<?=$msgAction;?>" class="" method="post" enctype="multipart/form-data">
              <div class="tile-body">
                <div class="form-group clearfix">
                  <?php
                  $levelx = [
                      '0'=> (object) ['level_id' => '1','level_category' => 'CATEGORY 01'],
                      '1'=> (object) ['level_id' => '2','level_category' => '02'],
                      '2'=> (object) ['level_id' => '3','level_category' => 'CAT'],
                  ];
                  // pp("$msglevel - $msgCategory - $msgCatName");
                  // pp($data);
                  // pp($level);
                  foreach ($level as $k => $v) :
                      if ($msglevel == $v->level_id) $checked = 'checked';
                      elseif ($k == 0) $checked = 'checked';
                      else $checked = '';
                      echo '<div class="float-left mr-5" >';
                          echo '<label class="control-label d-block"> '.ucfirst($v->level_name).' <small>( '.$v->level_category.' )</small> </label> ';
                          echo '<label class="switch mx-auto" style="min-widthx: 100px;">';
                              echo '<input class="form-check-input" type="radio" name="level_id" value="'.$v->level_id.'" '.$checked.'>';
                              echo '<span class="slider"></span>';
                          echo '</label>';
                      echo '</div>';
                  endforeach;
                  ?>
                </div>
                <div class="form-group">
                  <label class="control-label">Name</label>
                  <!-- <input type="hidden" name="level_id" value="<?=$msglevel?>" > -->
                  <input class="form-control" type="text" name="user_name" value="<?=$msgName;?>" placeholder="Enter full name">
                </div>
                <div class="form-group">
                  <label class="control-label">Email</label>
                  <input class="form-control" type="email" name="user_email" value="<?=$msgEmail?>" placeholder="Enter email address">
                </div>

                <div class="form-group ">
                    <label class="control-label">Password</label>
                    <div class="input-group">
                        <input type="password" name="user_password" value="<?=$msgShow?>" class="eyePassword form-control" placeholder="Informe a senha">
                        <span class="input-group-btn ml-2">
                            <a href="#"
                                class="btn btn-primary showpass"
                                title="Visualizar senha" alt="Visualizar senha"
                                aria-hidden="true"
                                >
                                <i class="fa fa-eye" aria-hidden="true"></i>
                            </a>
                        </span>
                    </div>
                </div>

                <div class="form-group">
                  <label class="control-label">Address</label>
                  <textarea class="form-control" rows="4" name="user_obs" placeholder="Enter your address"><?=$msgObs; ?></textarea>
                </div>

                <div class="form-group">
                  <label class="control-label">Identity Proof</label>
                  <input type="file" name="user_thumb" class="form-control" id="getPrevew">
                </div>

              </div>
              <div class="tile-footer">
                <button class="btn btn-primary" type="submit"><?=$btnAction?></button>
                &nbsp;&nbsp;&nbsp;
                <a class="btn btn-secondary pull-right" href="javascript:window.history.back();"><?=$btnBack?></a>
              </div>
            </form>
          </div>
        </div>

      </div>
    </main>



    <!-- Essential javascripts for application to work-->
    <script src="/assets/theme/js/jquery-3.2.1.min.js"></script>
    <script src="/assets/theme/js/popper.min.js"></script>
    <script src="/assets/theme/js/bootstrap.min.js"></script>
    <script src="/assets/theme/js/main.js"></script>
    <!-- The javascript plugin to display page loading on top-->
    <script src="/assets/theme/js/plugins/pace.min.js"></script>
    <!-- Page specific javascripts-->
    <script src="/assets/init.js"></script>
    <!-- Notification Plugin Bootstrap 4 Hullabaloo -->
    <!-- <script src="/assets/libs/Hullabaloo/hullabaloo.min.js"></script> -->
    <!-- <script src="/assets/libs/notify/notify.min.js"></script> -->
    <!-- Google analytics script-->

    <script type="text/javascript">

    </script>

  </body>
</html>