
<?php
    $uriBaseMidia = '/assets/midias';

    $view = $this->getData();
    $data = ($view['data'])?? '';

    // pp($data);

?>

<h3>Home</h3>
<?php
    showMessageFlash('primary');
    showMessageFlash('success');
    showMessageFlash('info');
    showMessageFlash('danger');
    showMessageFlash('warning');
?>
<p>
Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolorem tenetur cupiditate, debitis soluta! Dolorum adipisci laudantium, excepturi, non alias quod et iure officia, sunt illo corrupti? Molestias ut totam dolorum.
</p>

