<?php
	$view = $this->getData();
	$data = ($view['data'])?? '';

	// if ($data) {
        $formTitle  = '<h3> Edit Data </h3>';
        $btnAction  = '<i class="fa fa-edit m-right-xs"></i> Edit';
        $btnClass   = 'btn-warning';
        $msgId      = ($data->user_id) ?? '';
        $msglevel   = ($data->level_id) ?? '1';
        $msgName    = ($data->user_name) ?? '';
        $msgEmail   = ($data->user_email) ?? '';
        $msgObs     = ($data->user_obs) ?? '';
        $msgShow    = ($data->user_show) ?? '';
        $msgAuthor  = ($data->name_author) ?? '';
        /*$msgCreated = getDateTimePTbr($data->user_created);
        $msgUpdated = getDateTimePTbr($data->user_updated);*/
    // }

?>

<main role="main">

	<!-- Principal jumbotron, para a principal mensagem de marketing ou call to action -->
	<div class="jumbotron text-center">
		<div class="container">
			<img class="mb-4" src="/<?=PATH_LOGO2?>" alt="" >
			<h1 class="display-4"><?=$this->getTitle();?>!</h1>
			<p>Defina os dados de usuário master, para navegar o sistema!</p>

			<button type="button" class="btn btn-success mt-4" data-container="body" data-toggle="popover" data-placement="left" data-content="A conexão com banco de dados foi realizado com sucesso!"> SQLite 3 </button>

			<button type="button" class="btn btn-primary mt-4" data-container="body" data-toggle="popover" data-placement="bottom" data-content="Tabela do sistema foi criado com sucesso!"> Table System </button>

			<button type="button" class="btn btn-info mt-4" data-container="body" data-toggle="popover" data-placement="right" data-content="Utilize o formulário a baixo para criar usuário master!"> Master </button>
			<!-- <button class="btn btn-info mt-4" type="button"> Setting Master </button> -->
</span>

		</div>
	</div>

	<div class="container" style="min-height: 28rem;">
		<!-- Exemplo de linha de colunas -->
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
			<?php
				showMessageFlash('primary');
				showMessageFlash('success');
				showMessageFlash('info');
				showMessageFlash('warning');
				showMessageFlash('danger');
			?>

				<div class="d-nonex">
					<div class="card card-body">
						<h2>Create Master</h2>
						<form action="/setup/create-master" method="post" class="form-signin">

							<div class="form-group row">
								<label class="col-sm-3 col-form-label mt-2">Name</label>
								<div class="col-sm-9">
									<input type="text" name="user_name" class="form-control" value="<?=$msgName?>">
								</div>

								<label class="col-sm-3 col-form-label mt-2">Email</label>
								<div class="col-sm-9">
									<input type="email" name="user_email" class="form-control" value="<?=$msgEmail?>">
								</div>

								<label class="col-sm-3 col-form-label mt-2">Password</label>
								<div class="col-sm-9">
									<input type="password" name="user_password" class="form-control" value="<?=$msgShow?>">
								</div>
							</div>

							<button type="submit" class="btn btn-primary">Submit</button>
						</form>
					</div>
				</div>

			</div>
			<div class="col-md-2"></div>
		</div>
	</div>

	<hr>

	</div> <!-- /container -->

</main>

