<?php

	$view = $this->getData();
	$data = ($view['data'])?? '';

?>

<main role="main">

	<!-- Principal jumbotron, para a principal mensagem de marketing ou call to action -->
	<div class="jumbotron text-center">
		<div class="container">
			<img class="mb-4" src="/<?=PATH_LOGO2?>" alt="" >
			<h1 class="display-4">Settings DataBase!</h1>
			<p>Defina a melhor configuração para seu banco de dados!</p>

			<button class="btn btn-primary mt-4" type="button" id="btnSqlite"> SQLite 3 </button>
			<button class="btn btn-primary mt-4" type="button" id="btnMysql"> MySQL </button>
			<button class="btn btn-primary mt-4" type="button" id="btnOracle"> Oracle SQL </button>
			<button class="btn btn-primary mt-4" type="button" id="btnPostgres"> PostgreSQL </button>
			<button class="btn btn-primary mt-4" type="button" id="btnSqlserver"> SQL Server </button>
		</div>
	</div>

	<div class="container" style="min-height: 28rem;">
		<!-- Exemplo de linha de colunas -->
		<div class="row">
			<div class="col-md-2"></div>
			<div class="col-md-8">
			<?php
				showMessageFlash('primary');
				showMessageFlash('success');
				showMessageFlash('info');
				showMessageFlash('warning');
				showMessageFlash('danger');
			?>

				<div class="d-none" id="pnlSqlite">
					<div class="card card-body">
						<h2>SQLite3</h2>
						<form action="/setup/dbcreate" method="post" class="form-signin">

							<input type="hiddenx" name="DBDrive" class="form-control" value="sqlite">

							<div class="form-group row">
								<label class="col-sm-3 col-form-label mt-2">Database Host</label>
								<div class="col-sm-9">
									<input type="text" name="DBHost" class="form-control" value="<?=$data['sqlite']['DBHost']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Database Name</label>
								<div class="col-sm-9">
									<input type="text" name="DBName" class="form-control" value="<?=$data['sqlite']['DBName']?>">
								</div>

								<div style="display: none">
									<label class="col-sm-3 col-form-label mt-2">Username</label>
									<div class="col-sm-9">
										<input type="text" name="DBUser" class="form-control" value="--">
									</div>
									<label class="col-sm-3 col-form-label mt-2">Password</label>
									<div class="col-sm-9">
										<input type="text" name="DBPass" class="form-control" value="--">
									</div>
									<label class="col-sm-3 col-form-label mt-2">Charset</label>
									<div   class="col-sm-9">
										  <input type="text" name="DBCharset" class="form-control" value="--">
									</div>
									<label class="col-sm-3 col-form-label mt-2">Collation</label>
									<div class="col-sm-9  ">
										<input type="text" name="DBCollation" class="form-control" value="--">
									</div>
								</div>

							</div>

							<button type="submit" class="btn btn-primary">Submit</button>
						</form>
					</div>
				</div>

				<div class="d-none" id="pnlMysql">
					<div class="card card-body">
						<h2>MySQL</h2>
						<form action="/setup/dbcreate" method="post" class="form-signin">

							<input type="hiddenx" name="DBDrive" class="form-control" value="mysql">

							<div class="form-group row">
								<label class="col-sm-3 col-form-label mt-2">Database Host</label>
								<div class="col-sm-9">
									<input type="text" name="DBHost" class="form-control" value="<?=$data['mysql']['DBHost']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Database Name</label>
								<div class="col-sm-9">
									<input type="text" name="DBName" class="form-control" value="<?=$data['mysql']['DBName']?>">
								</div>

								<label class="col-sm-3 col-form-label mt-2">Username</label>
								<div class="col-sm-9">
									<input type="text" name="DBUser" class="form-control" value="<?=$data['mysql']['DBUser']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Password</label>
								<div class="col-sm-9">
									<input type="text" name="DBPass" class="form-control" value="<?=$data['mysql']['DBPass']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Charset</label>
								<div   class="col-sm-9">
									  <input type="text" name="DBCharset" class="form-control" value="<?=$data['mysql']['DBCharset']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Collation</label>
								<div class="col-sm-9  ">
									<input type="text" name="DBCollation" class="form-control" value="<?=$data['mysql']['DBCollation']?>">
								</div>

							</div>

							<button type="submit" class="btn btn-primary">Submit</button>
						</form>
					</div>
				</div>

				<div class="d-none" id="pnlOracle">
					<div class="card card-body">
						<h2>Oracle SQL</h2>
						<form action="/setup/dbcreate" method="post" class="form-signin">

							<input type="hiddenx" name="DBDrive" class="form-control" value="oracle">

							<div class="form-group row">
								<label class="col-sm-3 col-form-label mt-2">Database Host</label>
								<div class="col-sm-9">
									<input type="text" name="DBHost" class="form-control" value="<?=$data['oracle']['DBHost']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Database Name</label>
								<div class="col-sm-9">
									<input type="text" name="DBName" class="form-control" value="<?=$data['oracle']['DBName']?>">
								</div>

								<label class="col-sm-3 col-form-label mt-2">Username</label>
								<div class="col-sm-9">
									<input type="text" name="DBUser" class="form-control" value="<?=$data['oracle']['DBUser']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Password</label>
								<div class="col-sm-9">
									<input type="text" name="DBPass" class="form-control" value="<?=$data['oracle']['DBPass']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Charset</label>
								<div   class="col-sm-9">
									  <input type="text" name="DBCharset" class="form-control" value="<?=$data['oracle']['DBCharset']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Collation</label>
								<div class="col-sm-9  ">
									<input type="text" name="DBCollation" class="form-control" value="<?=$data['oracle']['DBCollation']?>">
								</div>

							</div>

							<button type="submit" class="btn btn-primary">Submit</button>
						</form>
					</div>
				</div>

				<div class="d-none" id="pnlPostgres">
					<div class="card card-body">
						<h2>PostgresSQL</h2>
						<form action="/setup/dbcreate" method="post" class="form-signin">

							<input type="hiddenx" name="DBDrive" class="form-control" value="postgres">

							<div class="form-group row">
								<label class="col-sm-3 col-form-label mt-2">Database Host</label>
								<div class="col-sm-9">
									<input type="text" name="DBHost" class="form-control" value="<?=$data['postgres']['DBHost']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Database Name</label>
								<div class="col-sm-9">
									<input type="text" name="DBName" class="form-control" value="<?=$data['postgres']['DBName']?>">
								</div>

								<label class="col-sm-3 col-form-label mt-2">Username</label>
								<div class="col-sm-9">
									<input type="text" name="DBUser" class="form-control" value="<?=$data['postgres']['DBUser']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Password</label>
								<div class="col-sm-9">
									<input type="text" name="DBPass" class="form-control" value="<?=$data['postgres']['DBPass']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Charset</label>
								<div   class="col-sm-9">
									  <input type="text" name="DBCharset" class="form-control" value="<?=$data['postgres']['DBCharset']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Collation</label>
								<div class="col-sm-9  ">
									<input type="text" name="DBCollation" class="form-control" value="<?=$data['postgres']['DBCollation']?>">
								</div>

							</div>

							<button type="submit" class="btn btn-primary">Submit</button>
						</form>
					</div>
				</div>

				<div class="d-none" id="pnlSqlserver">
					<div class="card card-body">
						<h2>SQL Server</h2>
						<form action="/setup/dbcreate" method="post" class="form-signin">

							<input type="hiddenx" name="DBDrive" class="form-control" value="sqlserver">

							<div class="form-group row">
								<label class="col-sm-3 col-form-label mt-2">Database Host</label>
								<div class="col-sm-9">
									<input type="text" name="DBHost" class="form-control" value="<?=$data['sqlserver']['DBHost']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Database Name</label>
								<div class="col-sm-9">
									<input type="text" name="DBName" class="form-control" value="<?=$data['sqlserver']['DBName']?>">
								</div>

								<label class="col-sm-3 col-form-label mt-2">Username</label>
								<div class="col-sm-9">
									<input type="text" name="DBUser" class="form-control" value="<?=$data['sqlserver']['DBUser']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Password</label>
								<div class="col-sm-9">
									<input type="text" name="DBPass" class="form-control" value="<?=$data['sqlserver']['DBPass']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Charset</label>
								<div   class="col-sm-9">
									  <input type="text" name="DBCharset" class="form-control" value="<?=$data['sqlserver']['DBCharset']?>">
								</div>
								<label class="col-sm-3 col-form-label mt-2">Collation</label>
								<div class="col-sm-9  ">
									<input type="text" name="DBCollation" class="form-control" value="<?=$data['sqlserver']['DBCollation']?>">
								</div>

							</div>

							<button type="submit" class="btn btn-primary">Submit</button>
						</form>
					</div>
				</div>

			</div>
			<div class="col-md-2"></div>
		</div>
	</div>

	<hr>

	</div> <!-- /container -->

</main>

