<?php

	$baseURI  = '/auth';

	$msgEmail = getDataInput('user_email') ?? '';
  	$msgSenha = getDataInput('user_password') ?? '';

?>

	<main role="main" class="inner cover">

		<?php

			showMessageFlash('primary');
			showMessageFlash('success');
			showMessageFlash('info');
			showMessageFlash('danger');
			showMessageFlash('warning');

		?>

		<form action="/auth/login" method="post" class="form-signin">
			<img class="mb-4" src="/<?=PATH_LOGO2?>" alt="" >

			<h1 class="h3 mb-3 font-weight-normal">Settings DB</h1>
			<p>Defina a melhor configuração para seu banco de dados!</p>

			<!--
				Database Name
				Username
				Password
				Database Host
				Table Prefix
			-->
			<div class="form-group row">
				<label for="inputEmail3" class="col-sm-2 col-form-label">Email</label>
				<div class="col-sm-10">
					<input type="email" class="form-control" id="inputEmail3" placeholder="Email">
				</div>
			</div>


			<!-- <label class="sr-only">Database Name</label>
			<input type="text" name="setup_x" class="form-control bpass" placeholder="Database Name" required>

			<label class="sr-only">Username</label>
			<input type="text" name="setup_x" class="form-control bpass" placeholder="Username" required>

			<label class="sr-only">Password</label>
			<input type="text" name="setup_x" class="form-control bpass" placeholder="Password" required>

			<label class="sr-only">Database Host</label>
			<input type="text" name="setup_x" class="form-control bpass" placeholder="Database Host" required>

			<label class="sr-only">Table Prefix</label>
			<input type="text" name="setup_x" value="" class="form-control bpass" placeholder="Table Prefix" required> -->

			<!--
			<label for="inputPassword" class="sr-only">Password</label>
			<input type="password" id="user_password" name="user_password" class="form-control bpass" placeholder="Password" requiredx>

			<div class="checkbox mb-3">
				<label>
					<input type="checkbox" value="remember-me"> Remember me
				</label>
			</div>
			 -->

			<button type="submit" class="btn btn-lg btn-primary btn-block">Submit</button>

			<!-- <p class="mt-4 mb-3 text-muted">
				forgot your password? <a href="/auth/forgot">click here</a>
				<br> new user? <a href="/auth/create">create new account</a>
			</p> -->
		</form>
	</main>


