<?php
	$view = $this->getData();
	$data = ($view['data'])?? '';

	// pp($data,1);

    # Create .Json Conexão DB sqlite
    $msgDrive_sqlite	=  !empty(getDataInput('sqlite_drive'))?? 'sqlite';
    $msgHost_sqlite   	=  !empty(getDataInput('sqlite_host'))?
    						getDataInput('sqlite_host') : $data['sqlite']['host'];
    $msgName_sqlite		=  !empty(getDataInput('sqlite_name'))?
    						getDataInput('sqlite_name') : $data['sqlite']['name'];
    $msgAttr1_sqlite   	=  !empty(getDataInput('sqlite_attr1'))?
    						getDataInput('sqlite_attr1') : $data['sqlite']['user'];
    $msgAttr2_sqlite   	=  !empty(getDataInput('sqlite_attr2'))?
    						getDataInput('sqlite_attr2') : $data['sqlite']['password'];
    $msgAttr3_sqlite   	=  !empty(getDataInput('sqlite_attr3'))?
    						getDataInput('sqlite_attr3') : $data['sqlite']['charset'];
    $msgAttr4_sqlite   	=  !empty(getDataInput('sqlite_attr4'))?
    						getDataInput('sqlite_attr4') : $data['sqlite']['collation'];

    # Create .Json Conexão DB mysql
    $msgDrive_mysql		=  !empty(getDataInput('mysql_drive'))? getDataInput('mysql_drive') : 'mysql';
    $msgHost_mysql		=  !empty(getDataInput('mysql_host'))?
    						getDataInput('mysql_host') : $data['mysql']['host'];
    $msgName_mysql   	=  !empty(getDataInput('mysql_name'))?
    						getDataInput('mysql_name') : $data['mysql']['name'];
    $msgUser_mysql   	=  !empty(getDataInput('mysql_user'))?
    						getDataInput('mysql_user') : $data['mysql']['user'];
    $msgPassword_mysql  =  !empty(getDataInput('mysql_password'))?
    						getDataInput('mysql_password') : $data['mysql']['password'];
    $msgCharset_mysql   =  !empty(getDataInput('mysql_charset'))?
    						getDataInput('mysql_charset') : $data['mysql']['charset'];
    $msgCollation_mysql =  !empty(getDataInput('mysql_collation'))?
    						getDataInput('mysql_collation') : $data['mysql']['collation'];

    # Create User MasterKey
	$msglevel   = ($data->level_id) ?? '1';
    $msgName    = ($data->user_name) ?? 'admin';
    $msgEmail   = ($data->user_email) ?? 'masterkey@mk.com';
    $msgShow    = ($data->user_show) ?? 'masterkey';


    // $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    // $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_OBJ);
?>

<main role="main">

	<form action="/setup" method="post" class="form-signin">
	<!-- Principal jumbotron, para a principal mensagem de marketing ou call to action -->
	<div class="jumbotron text-center">
		<div class="container">
			<img class="mb-4" src="/<?=PATH_LOGO2?>" alt="" >
			<h1 class="display-4"><?=$this->getTitle();?>!</h1>
			<p>Defina a melhor configuração para seu banco de dados!</p>

			<button class="btn btn-info mt-4" type="button" id="btnCon"> Drive de DB </button>
			<button class="btn btn-primary mt-4" type="button" id="btnUser"> User MasterKey </button>
			<button class="btn btn-secondary mt-4" id="btnSave" type="button"> Save datas </button>
		</div>
	</div>

	<div class="container" style="min-height: 28rem;">
		<!-- Exemplo de linha de colunas -->
		<div class="row">
			<div class="col-md-2"></div>

			<div class="col-md-8">
                <div class="d-nonex">
                    <div class="card card-body">
                        <!-- <h2>Create Master</h2> -->
                        <?php
							showMessageFlash('primary');
							showMessageFlash('success');
							showMessageFlash('info');
							showMessageFlash('warning');
							showMessageFlash('danger');
						?>
						<div class="" id="pnlCon">
							<nav>
								<ul class="nav nav-tabs mb-3" id="myTab" role="tablist">
									<li class="nav-item">
										<a class="nav-link active" id="sqlite-tab" data-toggle="tab" href="#sqlite" role="tab" aria-controls="sqlite" aria-selected="true">SQLite 3</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" id="mysql-tab" data-toggle="tab" href="#mysql" role="tab" aria-controls="mysql" aria-selected="false">MySQL</a>
									</li>
									<li class="nav-item">
										<a class="nav-link disabled" id="oracle-tab" data-toggle="tab" href="#oracle" role="tab" aria-controls="oracle" aria-selected="false">Oracle</a>
									</li>
									<li class="nav-item">
										<a class="nav-link disabled" id="postgres-tab" data-toggle="tab" href="#postgres" role="tab" aria-controls="postgres" aria-selected="false">PostgreSQL</a>
									</li>
									<li class="nav-item">
										<a class="nav-link disabled" id="sqlserver-tab" data-toggle="tab" href="#sqlserver" role="tab" aria-controls="sqlserver" aria-selected="false">SQL Server</a>
									</li>
								</ul>
                    		</nav>

							<div class="tab-content" id="myTabContent">

								<input type="hidden" name="DBDrive" id="DBDrive" class="form-control" value="sqlite-tab">

								<!-- panel SQLite3 -->
								<div class="tab-pane fade show active" id="sqlite" role="tabpanel" aria-labelledby="sqlite-tab">
									<div class="form-group row">
										<label class="col-sm-3 col-form-label mt-2">Database Host</label>
										<div class="col-sm-9">
											<!-- <input type="hidden" name="sqlite_drive" class="form-control" value="sqlite"> -->
											<input type="text" name="sqlite_host" class="form-control" value="<?=$msgHost_sqlite?>">
										</div>

										<label class="col-sm-3 col-form-label mt-2">Database Name</label>
										<div class="col-sm-9">
											<input type="text" name="sqlite_name" class="form-control" value="<?=$msgName_sqlite?>">
										</div>

										<label class="col-sm-3 col-form-label mt-2">Attributes</label>
										<div class="form-row col-sm-9">
											<div class="col">
												<input type="text" name="sqlite_attr1" class="form-control" value="<?=$msgAttr1_sqlite?>">
											</div>
											<div class="col">
												<input type="text" name="sqlite_attr2" class="form-control" value="<?=$msgAttr2_sqlite?>">
											</div>
										</div>
										<label class="col-sm-3 col-form-label mt-2">Attributes</label>
										<div class="form-row col-sm-9">
											<div class="col">
												<input type="text" name="sqlite_attr3" class="form-control" value="<?=$msgAttr3_sqlite?>">
											</div>
											<div class="col">
												<input type="text" name="sqlite_attr4" class="form-control" value="<?=$msgAttr4_sqlite?>">
											</div>
										</div>

									</div>
								</div>

								<!-- panel MYSQL -->
								<div class="tab-pane fade" id="mysql" role="tabpanel" aria-labelledby="mysql-tab">
									<div class="form-group row">
										<label class="col-sm-3 col-form-label mt-2">Database Host</label>
										<div class="col-sm-9">
											<!-- <input type="hiddenx" name="mysql_drive" class="form-control" value="mysql"> -->
											<input type="text" name="mysql_host" class="form-control" value="<?=$msgHost_mysql?>">
										</div>
										<label class="col-sm-3 col-form-label mt-2">Database Name</label>
										<div class="col-sm-9">
											<input type="text" name="mysql_name" class="form-control" value="<?=$msgName_mysql?>">
										</div>

										<label class="col-sm-3 col-form-label mt-2">Username</label>
										<div class="col-sm-9">
											<input type="text" name="mysql_user" class="form-control" value="<?=$msgUser_mysql?>">
										</div>
										<label class="col-sm-3 col-form-label mt-2">Password</label>
										<div class="col-sm-9">
											<input type="text" name="mysql_password" class="form-control" value="<?=$msgPassword_mysql?>">
										</div>
										<label class="col-sm-3 col-form-label mt-2">Charset</label>
										<div   class="col-sm-9">
											  <input type="text" name="mysql_charset" class="form-control" value="<?=$msgCharset_mysql?>">
										</div>
										<label class="col-sm-3 col-form-label mt-2">Collation</label>
										<div class="col-sm-9  ">
											<input type="text" name="mysql_collation" class="form-control" value="<?=$msgCollation_mysql?>">
										</div>

									</div>
								</div>

								<!-- panel Oracle -->
								<div class="tab-pane fade" id="oracle" role="tabpanel" aria-labelledby="oracle-tab"> Content Oracle </div>
								<!-- panel PostgreSQL -->
								<div class="tab-pane fade" id="postgres" role="tabpanel" aria-labelledby="postgres-tab"> Content PostgreSQL </div>
								<!-- panel SQL Server -->
								<div class="tab-pane fade" id="sqlserver" role="tabpanel" aria-labelledby="sqlserver-tab"> Content SQL Server </div>
							</div>
                        </div>

                        <div class="d-none" id="pnlUser">
                        	<div class="form-group row">
							<label class="col-sm-3 col-form-label mt-2">Name</label>
							<div class="col-sm-9">
								<input type="text" name="user_name" class="form-control" value="<?=$msgName?>">
							</div>

							<label class="col-sm-3 col-form-label mt-2">Email</label>
							<div class="col-sm-9">
								<input type="email" name="user_email" class="form-control" value="<?=$msgEmail?>">
							</div>

							<label class="col-sm-3 col-form-label mt-2">Password</label>
							<div class="col-sm-9">
								<input type="password" name="user_password" class="form-control" value="<?=$msgShow?>">
							</div>
						</div>
                        </div>

                        <!-- </form> -->
                    </div>
                </div>
            </div>

			<div class="col-md-2"></div>
		</div>
	</div>

	<hr>

	</div> <!-- /container -->
	</form>

</main>

