<?php
	$view = $this->getData();
    $data = ($view['data'])?? '';
    $dbases  = $data['dbasesDefault'];
    $user    = $data['userDefault'];
    $project = $data['projectDefault'];
	// pp($data,1);

    # Create var MsgForm
    foreach ($data['dbasesDefault'] as $k => $v) {
        $v['drive'] = $k;
        // pp($v);
        foreach ($v as $field => $value) {
            # create name var
            $msg = str_replace($field, ucfirst($field), "msg{$field}_{$k}");
            # add value in var
            $$msg = !empty(getDataInput("{$k}_{$field}"))? getDataInput("{$k}_{$field}") : $v[$field];
        }
    }

    # Create User MasterKey
    $msglevel     = ($user['level_id']) ?? '';
	$msglevelName = ($user['level_name']) ?? '';
    $msgName      = ($user['user_name']) ?? '';
    $msgEmail     = ($user['user_email']) ?? '';
    $msgShow      = ($user['user_password']) ?? '';

    # Create Project
    $msgProjType      = ($project['proj_type']) ?? 'CMS';
    $msgProjKey       = ($project['proj_key']) ?? 'masterkey';
    $msgProjTitle     = ($project['proj_title']) ?? '1';
    $msgProjSlogan    = ($project['proj_slogn']) ?? 'admin';
    $msgProjMidias    = ($project['proj_midias']) ?? 'admin';
    $msgProjPaginator = ($project['proj_paginator']) ?? 'admin';


    // $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    // $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE, PDO::FETCH_OBJ);
?>

<main role="main">

	<form action="/setup" method="post" class="form-signin">
	<!-- Principal jumbotron, para a principal mensagem de marketing ou call to action -->
	<div class="jumbotron text-center">
		<div class="container">
			<img class="mb-4" src="/<?=PATH_LOGO2?>" alt="" >
			<h1 class="display-4"><?=$this->getTitle();?>!</h1>
			<p>Defina a melhor configuração para seu banco de dados!</p>

			<button class="btn btn-primary mt-4" type="button" id="btnCon"> Drives </button>
			<button class="btn btn-secondary mt-4" type="button" id="btnProject"> App </button>
            <button class="btn btn-secondary mt-4" type="button" id="btnUser"> Suport </button>
			<button class="btn btn-secondary mt-4" id="btnSave" type="button"> Save </button>
		</div>
	</div>

	<div class="container" style="min-height: 28rem;">
		<!-- Exemplo de linha de colunas -->
		<div class="row">
			<div class="col-md-2"></div>

			<div class="col-md-8">
                <div class="d-nonex">
                    <div class="card card-body">
                        <!-- <h2>Create Master</h2> -->
                        <?php
							showMessageFlash('primary');
							showMessageFlash('success');
							showMessageFlash('info');
							showMessageFlash('warning');
							showMessageFlash('danger');
                            // pp($data);
                            /*$e=\FwBD\Encrypt\Encrypt::hashCode('suporte');
                            pp($e);
                            $x=\FwBD\Encrypt\Encrypt::hashCode('suporte','@AppName$2018%');
                            pp($x,1);*/
						?>
						<div class="" id="pnlCon">
							<nav>
								<ul class="nav nav-tabs mb-3" id="myTab" role="tablist">
									<li class="nav-item">
										<a class="nav-link active" id="sqlite-tab" data-toggle="tab" href="#sqlite" role="tab" aria-controls="sqlite" aria-selected="true">SQLite 3</a>
									</li>
									<li class="nav-item">
										<a class="nav-link" id="mysql-tab" data-toggle="tab" href="#mysql" role="tab" aria-controls="mysql" aria-selected="false">MySQL</a>
									</li>
									<!-- <li class="nav-item">
                                        <a class="nav-link disabled" id="oracle-tab" data-toggle="tab" href="#oracle" role="tab" aria-controls="oracle" aria-selected="false">Oracle</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link disabled" id="postgres-tab" data-toggle="tab" href="#postgres" role="tab" aria-controls="postgres" aria-selected="false">PostgreSQL</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link disabled" id="sqlserver-tab" data-toggle="tab" href="#sqlserver" role="tab" aria-controls="sqlserver" aria-selected="false">SQL Server</a>
                                    </li> -->
								</ul>
                    		</nav>

							<div class="tab-content" id="myTabContent">

								<input type="hidden" name="DBDrive" id="DBDrive" class="form-control" value="sqlite-tab">

								<!-- panel SQLite3 -->
								<div class="tab-pane fade show active" id="sqlite" role="tabpanel" aria-labelledby="sqlite-tab">
									<div class="form-group row">
										<label class="col-sm-3 col-form-label mb-2">Database Host</label>
										<div class="col-sm-9">
											<input type="text" readonly name="sqlite_host" class="form-control" value="<?=$msgHost_sqlite?>">
										</div>

										<label class="col-sm-3 col-form-label mb-2">Database Name</label>
										<div class="col-sm-9">
											<input type="text" name="sqlite_name" class="form-control" value="" placeholder="Ex: <?=$msgName_sqlite?>">
										</div>

										<label class="col-sm-3 col-form-label mb-2">Attributes</label>
										<div class="form-row col-sm-9">
											<div class="col">
												<input type="text" name="sqlite_attr1" class="form-control" value="<?=$msgUser_sqlite?>">
											</div>
											<div class="col">
												<input type="text" name="sqlite_attr2" class="form-control" value="<?=$msgPassword_sqlite?>">
											</div>
										</div>
										<label class="col-sm-3 col-form-label mb-2">Attributes</label>
										<div class="form-row col-sm-9">
											<div class="col">
												<input type="text" name="sqlite_attr3" class="form-control" value="<?=$msgCharset_sqlite?>">
											</div>
											<div class="col">
												<input type="text" name="sqlite_attr4" class="form-control" value="<?=$msgCollation_sqlite?>">
											</div>
										</div>

									</div>
								</div>

								<!-- panel MYSQL -->
								<div class="tab-pane fade" id="mysql" role="tabpanel" aria-labelledby="mysql-tab">
									<div class="form-group row">
										<label class="col-sm-3 col-form-label mb-2">Database Host</label>
										<div class="col-sm-9">
											<input type="text" name="mysql_host" class="form-control" value="" placeholder="Ex: <?=$msgHost_mysql?>">
										</div>
										<label class="col-sm-3 col-form-label mb-2">Database Name</label>
										<div class="col-sm-9">
											<input type="text" name="mysql_name" class="form-control" value="" placeholder="Ex: <?=$msgName_mysql?>">
										</div>

										<label class="col-sm-3 col-form-label mb-2">Username</label>
										<div class="col-sm-9">
											<input type="text" name="mysql_user" class="form-control" value="" placeholder="Ex: <?=$msgUser_mysql?>">
										</div>
										<label class="col-sm-3 col-form-label mb-2">Password</label>
										<div class="col-sm-9">
											<input type="text" name="mysql_password" class="form-control" value="" placeholder="Ex: <?=$msgPassword_mysql?>">
										</div>
										<label class="col-sm-3 col-form-label mb-2">Charset</label>
										<div   class="col-sm-9">
											  <input type="text" name="mysql_charset" class="form-control" value="<?=$msgCharset_mysql?>">
										</div>
										<label class="col-sm-3 col-form-label mb-2">Collation</label>
										<div class="col-sm-9  ">
											<input type="text" name="mysql_collation" class="form-control" value="<?=$msgCollation_mysql?>">
										</div>

									</div>
								</div>

								<!-- panel Oracle -->
								<div class="tab-pane fade" id="oracle" role="tabpanel" aria-labelledby="oracle-tab"> Content Oracle </div>
								<!-- panel PostgreSQL -->
								<div class="tab-pane fade" id="postgres" role="tabpanel" aria-labelledby="postgres-tab"> Content PostgreSQL </div>
								<!-- panel SQL Server -->
								<div class="tab-pane fade" id="sqlserver" role="tabpanel" aria-labelledby="sqlserver-tab"> Content SQL Server </div>
							</div>
                        </div>

                        <div class="d-none" id="pnlProject">
                            <div class="form-group row">

                                <label class="col-sm-3 col-form-label mb-2">App Type</label>
                                <div class="col-sm-9">
                                    <input type="text" name="proj_category" class="form-control" value="<?=$msgProjType?>" placeholder="Ex: <?=$msgProjType?>">
                                </div>

                                <label class="col-sm-3 col-form-label mb-2">App Key</label>
                                <div class="col-sm-9">
                                    <input type="text" name="proj_key" class="form-control" value="<?=$msgProjKey?>">
                                </div>

                                <label class="col-sm-3 col-form-label mb-2">App Title</label>
                                <div class="col-sm-9">
                                    <input type="text" name="proj_title" class="form-control" value="" placeholder="Ex: <?=$msgProjTitle?>">
                                </div>

                                <label class="col-sm-3 col-form-label mb-2">App Slogan</label>
                                <div class="col-sm-9">
                                    <input type="text" name="proj_slogan" class="form-control" value="" placeholder="Ex: <?=$msgProjSlogan?>">
                                </div>

                                <label class="col-sm-3 col-form-label mb-2">App Paginator</label>
                                <div class="col-sm-9">
                                    <input type="text" name="proj_paginator" class="form-control" value="<?=$msgProjPaginator?>">
                                </div>

                                <label class="col-sm-3 col-form-label mb-2">Path Mídias</label>
                                <div class="col-sm-9">
                                    <input type="text" readonly name="proj_midias" class="form-control" value="<?=$msgProjMidias?>">
                                </div>

                            </div>
                        </div>

                        <div class="d-none" id="pnlUser">
                        	<div class="form-group row">
    							<label class="col-sm-3 col-form-label mb-2">Level</label>
    							<div class="col-sm-9">
                                    <input type="hidden" name="level_id" value="<?=$msglevel?>">
    								<input type="text" name="level_name" class="form-control" value="<?=$msglevelName?>" placeholder="Ex: <?=$msglevelName?>">
    							</div>

                                <label class="col-sm-3 col-form-label mb-2">Name</label>
                                <div class="col-sm-9">
                                    <input type="text" name="user_name" class="form-control" value="" placeholder="Ex: <?=$msgName?>">
                                </div>

    							<label class="col-sm-3 col-form-label mb-2">Email</label>
    							<div class="col-sm-9">
    								<input type="email" name="user_email" class="form-control" value="" placeholder="Ex: <?=$msgEmail?>">
    							</div>

    							<label class="col-sm-3 col-form-label mb-2">Password</label>
    							<div class="col-sm-9">
    								<input type="password" name="user_password" class="form-control" value="" placeholder="Ex: <?=$msgShow?>">
    							</div>
    						</div>
                        </div>

                        <!-- </form> -->
                    </div>
                </div>
            </div>

			<div class="col-md-2"></div>
		</div>
	</div>

	<hr>

	</div> <!-- /container -->
	</form>

</main>

