
<div class="clean"></div>
<hr>
<!-- Footer Session -->
  <footer class="footer">
    <div class="container">
      <span class="text-muted pull-right">
        &copy 2018 - <?=APP_HEADER?> Todos os direitos reservados.
        <a href="http://brunodamiao.com.br" target="_blank">by designer Bruno</a>
      </span>
    </div>
  </footer>


	<!-- jQuery Fonts
  ================================================== -->
  <script src="/assets/admin/Bruno/js/jquery.min.js"></script>
  <!-- FancyBox Scripts
  ================================================== -->
  <script src="/assets/fancybox/jquery.fancybox.min.js"></script>
  <!-- Codemirror JavaScript
  ================================================== -->
  <script src="/assets/codemirror/lib/codemirror.js"></script>    
  <script src="/assets/codemirror/mode/javascript/javascript.js"></script>
  <script src="/assets/codemirror/addon/selection/active-line.js"></script>
  <script src="/assets/codemirror/addon/edit/matchbrackets.js"></script>
  <!-- Custom AdminJS-Bruno Scripts
  ================================================== -->
  <script src="/assets/admin/Bruno/js/adminjs.js"></script>
  
  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="/assets/admin/themes/js/bootstrap.min.js"></script>
  <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
  <script src="/assets/admin/themes/js/holder.min.js"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="/assets/admin/themes/js/ie10-viewport-bug-workaround.js"></script>

  <!-- Froala wysiwyg Scripts
  ================================================== -->
    <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.js"></script> -->  
    <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/mode/xml/xml.min.js"></script> -->

    <!-- <script src="/assets/wysiwyg-froala/js/froala_editor.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/align.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/code_beautifier.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/code_view.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/colors.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/draggable.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/emoticons.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/font_size.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/font_family.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/image.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/file.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/image_manager.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/line_breaker.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/link.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/lists.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/paragraph_format.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/paragraph_style.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/video.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/table.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/url.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/entities.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/char_counter.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/inline_style.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/save.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/fullscreen.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/quick_insert.min.js"></script>
    <script src="/assets/wysiwyg-froala/js/plugins/quote.min.js"></script> -->

</body>
</html>