<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="../<?=PATH_FAVICON?>" /> 

    <title> <?=APP_HEADER?> - <?=$this->getTitle();?> </title>

    <!-- Bootstrap core CSS -->
    <link href="/assets/admin/themes/css/bootstrap.min.css" rel="stylesheet">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <!-- <link href="/assets/admin/themes/font-awesome3.0/css/font-awesome.min.css" rel="stylesheet"> -->

    <!-- Froala wysiwyg css -->
      <!-- <link rel="stylesheet" href="/assets/wysiwyg-froala/css/froala_editor.min.css"> -->
      <!-- <link rel="stylesheet" href="/assets/wysiwyg-froala/css/froala_style.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/code_view.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/colors.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/emoticons.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/image_manager.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/image.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/line_breaker.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/table.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/char_counter.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/video.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/fullscreen.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/quick_insert.min.css">
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/plugins/file.min.css">
      
      <link rel="stylesheet" href="/assets/wysiwyg-froala/css/themes/dark.min.css"> -->

      <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.3.0/codemirror.min.css"> -->

    <!-- Codemirror css -->
    <link rel="stylesheet" href="/assets/codemirror/lib/codemirror.css">
    <link rel="stylesheet" href="/assets/codemirror/theme/material.css">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="/assets/admin/themes/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/assets/admin/themes/css/dashboard.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/assets/admin/themes/js/ie-emulation-modes-warning.js"></script>

    <!-- Custom Style BRUNO -->
    <link href="/assets/admin/Bruno/css/style.css" rel="stylesheet">
    <!-- FancyBox Style -->
    <link href="/assets/fancybox/jquery.fancybox.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
<body>

<?php
# SESSION
$authSession = (object) FwBD\Session\Session::get('Auth');
// pp($authSession);
?>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Project name</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/admin">Dashboard</a></li>
        
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Settings <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="/admin/category">Category System </a></li>
            <li><a href="/admin/level">Level auth</a></li>
            <!-- <li><a href="/admin/user">User</a></li> -->
            <li role="separator" class="divider"></li>
            <li><a href="/admin/budget"> Budget </a></li>
            <li><a href="/admin/testimonials"> Testimonials </a></li>
            <li><a href="/admin/services"> Services </a></li>
            <li><a href="/admin/newsletter"> Newsletter </a></li>
          </ul>
        </li>

        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Users <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="/admin/user">User App</a></li>
            <li><a href="/admin/user">User EAD</a></li>
          </ul>
        </li>

        <!-- <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Blogs <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="/admin/blog-category"> Category </a></li> category (noma da lista)
            <li><a href="/admin/blog-article"> Article </a></li> formulários de inscrição
            <li role="separator" class="divider"></li>
            <li><a href="/admin/blog-comments"> <i class="fas fa-paper-plane"></i> Comments </a></li>  programar os e-maisl X campanhas
          </ul>
        </li> -->

        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
            Marketing <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><a href="/admin/campaigns">Campaigns </a></li> <!-- category (noma da lista) -->
            <li><a href="/admin/webforms">WebForms </a></li> <!-- formulários de inscrição -->
            <li><a href="/admin/leads">Leads </a></li> <!-- add contatos -->
            <li><a href="/admin/newsletter">Newsletter</a></li> <!-- criar rasc. de emails -->
            <li role="separator" class="divider"></li>
            <li><a href="/admin/responder"> <i class="fas fa-paper-plane"></i> Send E-mails</a></li>  <!-- programar os e-maisl X campanhas -->
          </ul>
        </li>

        <li><a href="/admin/user/profile/<?=$authSession->session_user?>">Profile</a></li>
        <li><a href="/auth/logout">Logout</a></li>
      </ul>

      <!-- <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form> -->

    </div>
  </div>
</nav>