<?php

  $authSession = (object) FwBD\Session\Session::get('Auth');
  $baseURI  = '/admin/user';
  $view     = $this->getData();
  $data     = $view['data'];
  $dataForm = ($view['dataForm'])?? '';

?>  

<h3 class="sub-header"> List data 
  <a href="<?=$baseURI;?>/create">
  <div class="btn btn-primary pull-right">
    <span class="fa fa-plus-circle" aria-hidden="true"></span> Create new </div> 
  </a>
</h3>

  <?php
    showMessageFlash('primary');
    showMessageFlash('success');
    showMessageFlash('info');
    showMessageFlash('danger');
    showMessageFlash('warning');
    // pp($authSession);
    // pp($data->getResult());
  ?>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Level</th>
        <th>Date</th>
        <th>Author</th>
        <th>Status</th>
        <th style="width: 20%">Actions</th>
      </tr>
    </thead>
    <tbody>
      <?php        
        
        if ( ! $data->getResult() ) {
          echo "<tr>";
            echo "<td colspan='8'> <center> <span>Sem Registro</span> </center> </td>";
          echo "</tr>";
        }

        foreach ($data->getResult() as $k => $user) :
          $action    = ($user->user_status)? 'value="1" checked' : 'value="0" ';
          $user_id   = ($user->user_id)?? $user->id;
          $user_name = ($user->user_name)?? $user->name;
          $nameAuthor= ($user->name_author)? $user->name_author : 'masterkey';
          echo "<tr>";
            echo "<td>{$user->user_id}</td>";
            echo "<td>{$user->user_name}</td>";
            echo "<td> <small>{$user->level_category} - ".strtoupper($user->level_name)."</small></td>";
            echo '<td>';
              echo '<small>create '.date('d-m-Y',strtotime($user->user_created));
              echo '<br> update '.date('d-m-Y', strtotime($user->user_updated)).'</small>';
            echo '</td>';
            echo "<td>{$nameAuthor}</td>";
            
            echo "<td>";
              echo '<label class="switch">';
                  echo '<input type="checkbox" 
                    class="sts" '.$action.'
                    data-model="user/jstatus" 
                    data-id="'.$user_id.'" 
                    data-name="'.$user_name.'">';
                  echo '<span class="slider round"></span>';
              echo '</label>';
            echo "</td>";
            
            echo '<td>';
              // echo '<a href="'.$baseURI.'/preview/'.$user->user_id.'" class="btn btn-info btn-xs" title="Detalhes do usuário" alt="Detalhes do usuário"> <i class="fas fa-user m-right-xs"></i> View </a> ';
              echo '<a href="'.$baseURI.'/edit/'.$user->user_id.'" class="btn btn-warning btn-xs" title="Edit Registro" alt="Edit Registro"> <i class="fa fa-edit m-right-xs"></i> Edit </a> ';
              echo '<a href="'.$baseURI.'/delete/'.$user->user_id.'" class="btn btn-danger btn-xs" title="Delete Registro" alt="Delete Registro"> <i class="fas fa-trash-alt m-right-xs"></i> Delete </a> ';
            echo '</td>';

            /*echo '<td><a href=""> <i class="fas fa-image"></i> </a></td>';
            echo '<td><a href=""> <i class="fas fa-edit"></i> </a></td>';
            echo '<td><a href=""> <i class="fas fa-trash-alt"></i> </a></td>';*/
          echo "</tr>";
        endforeach;
      ?>
    </tbody>
  </table>
</div>